- name: "Github"
  code: github
- name: "Authy"
  code: authy
- name: "Google Chrome"
  code: google-chrome
- name: "Microsoft Edge"
  code: microsoft-edge
- name: "Vivaldi Browser"
  code: vivaldi
- name: "Brave Browser"
  code: brave-browser
- name: "Lasspass"
  code: lastpass
- name: "Discord"
  code: discord
- name: "Visual Paradigm CE"
  code: visual-paradigm-ce
- name: "DBEaver Community Edittion"
  code: dbeaver-community
- name: "PgAdmin 4"
  code: pgadmin4
- name: "TextMate"
  code: textmate
- name: "Keeweb"
  code: keeweb
- name: "Spectacle"
  code: spectacle
- name: "Free Download Manager"
  code: free-download-manager
- name: "Wireshark"
  code: wireshark
- name: "PGP Suite"
  code: gpg-suite
- name: "Draw.io"
  code: drawio
- name: "Skitch"
  code: skitch
- name: "Postman"
  code: postman
- name: "OpenKey"
  code: openkey
- name: "Monitor Control"
  code: monitorcontrol
- name: "Transmission"
  code: "transmission"
- name: "Hyper Terminal"
  code: hyper
- name: "GraphQL Playground"
  code: graphql-playground
- name: "OSX FUSE"
  code: macfuse
- name: "Source Trail"
  code: sourcetrail
- name: "Image Optim"
  code: imageoptim
- name: "Tor Browser"
  code: tor-browser